/**
 * Task interface matching backend model from Feature 003/004
 *
 * Represents a todo item with all properties from the database model.
 * Used for type-safe API communication and component props.
 *
 * Feature 006: Task Organization & Usability Enhancements
 * - Added priority field (high/medium/low)
 * - Added tags field (array of strings)
 */

/** Task priority levels */
export type TaskPriority = 'high' | 'medium' | 'low';

export interface Task {
  /** Unique task identifier (auto-generated by backend) */
  id: number;

  /** ID of the user who owns this task */
  user_id: string;

  /** Task title (required, 1-200 characters) */
  title: string;

  /** Optional task description (max 1000 characters) */
  description: string | null;

  /** Completion status (true if complete, false if incomplete) */
  completed: boolean;

  /** Task priority level (high, medium, or low) - default: medium */
  priority: TaskPriority;

  /** Array of tag strings for categorization */
  tags: string[];

  /** Timestamp when task was created (UTC) */
  created_at: string;

  /** Timestamp when task was last updated (UTC) */
  updated_at: string;
}

/**
 * TaskCreate interface for creating new tasks
 * Matches backend TaskCreate schema
 */
export interface TaskCreate {
  /** Task title (required, 1-200 characters) */
  title: string;

  /** Optional task description (max 1000 characters) */
  description?: string;

  /** Optional priority level (default: medium) */
  priority?: TaskPriority;

  /** Optional tags array (default: []) */
  tags?: string[];
}

/**
 * TaskUpdate interface for updating existing tasks
 * Matches backend TaskUpdate schema
 * All fields optional for partial updates
 */
export interface TaskUpdate {
  /** Updated task title (1-200 characters if provided) */
  title?: string;

  /** Updated task description (max 1000 characters if provided) */
  description?: string;

  /** Updated completion status */
  completed?: boolean;

  /** Updated priority level */
  priority?: TaskPriority;

  /** Updated tags array (replaces existing tags) */
  tags?: string[];
}
